a_workflow_publish:
  url: /admin/workflow/publish
  params:
    module: aWorkflow
    action: publish

a_workflow_set_mode:
  url: /admin/workflow/set-mode
  params:
    module: aWorkflow
    action: setMode